// package 3Patterns.Day1_Hashing.Hashset;

import java.util.HashSet;

public class Main {

    public static void main(String[] args) {

        HashSet<Integer> set = new HashSet<>();  // HashSet does not maintain any order of elements

        set.add(10);// is this is in the index 0 or not? No, because HashSet does not maintain any order of elements
        set.add(20);  // so how it access the element? It uses the hashcode of the element to access it in O(1) time complexity
        set.add(30);  // what is hashcode? It is a unique identifier for each element in the set, it is generated by the hash function of the element, it is used to access the element in O(1) time complexity

        System.out.println(set);

        System.out.println(set.contains(20));

        set.remove(20);

        System.out.println(set);

        System.out.println(set.size());
    }
}